### ISSUE TITLE
Keep nrpe_local.cfg include

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack-formulas/nagios-formula#52]
On debian stretch the following line is removed by the formula : 

```
include=/etc/nagios/nrpe_local.cfg
```

It would be nice to keep it (or have a way to add it via pillars)

**Comment by mgomersbach** [comment]
This doable by setting the file in a seperate dir and then setting the lookup dict:
```
nagios:
  lookup:
    nrpe:
      cfg_dir: /path/to/your/includes
```
